fix #326 by lazy-requiring js-beautify
ajv-validator/ajv pull request #327
Opened 2016-10-18 16:05 UTC by danyshaanan

**What issue does this pull request resolve?**
https://github.com/epoberezkin/ajv/issues/326

**What changes did you make?**
"require js-beautify lazily (but still synchronously), only if beautify option was specified" (@EtaiG)

**Is there anything that requires more attention while reviewing?**
Not that I can think of.

---

`npm test` passed successfully. (locally).

If anything additional is required, please specify so that we could follow up on this.

Thanks.

2016-10-18 19:53 UTC, epoberezkin requested changes

2016-10-18 19:53 UTC, epoberezkin commented on lib/compile/index.js
> +      loadBeautifyIfNeeded();
Could we simplify a bit? Something like:

```javascript
if (beautify === undefined) {
  beautify = (function() {
    try { return require('' + 'js-beautify').js_beautify; }
    catch(e) { beautify = false }
  })();
}
```

No need to create two new names really...

2016-10-19 06:34 UTC, EtaiG commented on lib/compile/index.js
> +      loadBeautifyIfNeeded();
sure, on it.

2016-10-19 07:34 UTC, epoberezkin commented
I merged it (with some corrections - removed whitespace changes and made it function back again...)
try catch should be in a separate function (that's why it was in closure in my sample), v8 doest use optimising compiler for the whole function with try/catch (see https://bugs.chromium.org/p/v8/issues/detail?id=1065).

2016-10-19 07:34 UTC, closed without merging

2016-10-19 07:59 UTC, EtaiG commented
Cool, interesting to know 👍 

I didn't know that code inside an IIFE is not optimized as part of the function either (meaning the optimization won't take a hit for unoptimized code there)

2016-10-19 08:03 UTC, EtaiG commented
Also, can you let me know when the package.json is updated with a version I can use for this? 

Thanks for the quick turnaround!

2016-10-19 08:41 UTC, epoberezkin commented
In 4.8.1
Thank you, it was the right thing to do.