Add allowRefComments option
ajv-validator/ajv pull request #867
Opened 2018-10-07 15:12 UTC by FloEdelmann

**What issue does this pull request resolve?**

Closes issue #686.

**What changes did you make?**

A new boolean option `allowRefComments`. If it is set to `false` (default), everything works as before. If it is set to true, `$comment` is allowed alongside `$ref` in schemas (and does not cause a log message) when `extendRefs` is set to "ignore" or "fail".

**Is there anything that requires more attention while reviewing?**

I don't think so.

2018-11-04 21:04 UTC, epoberezkin requested changes
Thank you. I suggest dropping an extra option - it will make the change much simpler.

2018-11-04 21:04 UTC, epoberezkin commented on lib/compile/util.js
> +  return false;
not necessary

2018-11-04 21:04 UTC, epoberezkin commented on README.md
> +  allowRefComments: false,
I prefer simply always ignoring $comment with $ref, without any extra option.

2018-11-04 21:04 UTC, epoberezkin commented on lib/compile/util.js
> +  return false;
this change will be much simpler as $comment can be just used here directly

2018-11-04 21:04 UTC, epoberezkin commented on lib/dot/validate.jst
> +    , $refKeywords = it.util.schemaHasRulesExcept(it.schema, it.RULES.all, (it.opts.allowRefComments ? ['$ref', '$comment'] : ['$ref']))
without option - no change here

2018-11-07 16:30 UTC, FloEdelmann commented
Removing the option yields to other failing tests:

```
  1) Ajv Options
       $comment
         = true
           should log the text from $comment keyword:

      AssertionError: expected [] to deeply equal [ [ 'property foo' ] ]
      + expected - actual

      -[]
      +[
      +  [
      +    "property foo"
      +  ]
      +]
      
      at test (spec/options.spec.js:1300:30)
      at /home/flo/www/ajv/spec/options.spec.js:1293:11
      at Array.forEach (<anonymous>)
      at Context.<anonymous> (spec/options.spec.js:1289:24)

  2) Ajv Options
       $comment
         function hook
           should pass the text from $comment keyword to the hook:

      AssertionError: expected [] to deeply equal [ Array(1) ]
      + expected - actual

      -[]
      +[
      +  [
      +    "property foo"
      +    "#/properties/foo/$comment"
      +    {
      +      "properties": {
      +        "bar": {
      +          "$comment": "property bar"
      +          "type": "integer"
      +        }
      +        "foo": {
      +          "$comment": "property foo"
      +        }
      +      }
      +    }
      +  ]
      +]
      
      at test (spec/options.spec.js:1341:31)
      at /home/flo/www/ajv/spec/options.spec.js:1330:11
      at Array.forEach (<anonymous>)
      at Context.<anonymous> (spec/options.spec.js:1326:24)
```

2018-11-09 23:16 UTC, epoberezkin commented
Well, these tests should pass - they specifically test that the content of $comment itself should be logged when this option $comment is enabled - it is not related to the problem this PR should be addressing.

2019-01-24 22:21 UTC, Teoxoy commented
Are the tests passing now?

2019-02-09 12:26 UTC, epoberezkin commented
Tests pass but the changes are not updated I think.

2019-02-12 12:48 UTC, FloEdelmann commented
Sorry this took so long :see_no_evil:

I've updated the code, but the same errors remain. I've short-circuited the precommit hook to show you my current version. Do you have any suggestions what could interfere with the `$comment` option working correctly?

2019-02-12 19:33 UTC, epoberezkin commented
No problem with the time - thanks for the contribution.

The change should allow comments and refs in the same schema object, if I understand it correctly. I don’t see how it should affect any of the existing tests (unless you change them).

The additional tests you need should tests that with the comments and ref together Ajv doesn’t throw but it still logs comments (or calls hook).

What am I missing?

2019-02-12 20:10 UTC, FloEdelmann commented
I had one more look and sorted out what was still missing :tada: 
So I think this is now ready to review @epoberezkin :)

2019-03-10 13:15 UTC, FloEdelmann commented
Any updates about this @epoberezkin?

2019-05-09 11:33 UTC, FloEdelmann commented
Still no news about this PR?

2020-07-06 19:54 UTC, lsirivong commented
👋 hello! I just ran into this. Any update on when this might be able to ship?

2020-11-15 14:30 UTC, epoberezkin commented
this is no longer an issue in v7, closing

2020-11-15 14:30 UTC, closed without merging